### ISSUE TITLE
RoadMap

### ISSUE THREAD

**Issue by jmcardon** [jmcardon/tsec#7]
Below is our general roadmap:

## RoadMap essentials for first version:

JCA:
- [x] MessageDigests
- [x] MessageDigests Testing
- [x] Symmetric ciphers (Missing PBE, blowfish and ARCFOUR)
- [x] Symmetric Cipher tests
- [x] KeyGenerators for ciphers and macs
- [x] KeyGenerator for mac
- [x] KeySpec
- [x] Mac
- [x] Mac tests
- [x] Signatures (Relies on bouncy castle)
- [x] Signature Tests

Password Hashing:
- [x] BCrypt (jBCrypt)
- [x] SCrypt (wg/scrypt)
- [x] Password hasher tests

Server-side app goodies
- [x] JWS/JWT implementation (WIP)
- [x] JWT testing(Mac)
- [x] JWT testing(Signatures)
- [ ] Common session token crypto schemes and tests
- [ ] Http4s authentication and tests

## Nice to haves(future):

JCA
- [ ] Asymmetric Ciphers (WIP by robert)
- [ ] Asymmetric Cipher tests
- [ ] AlgorithmParameters nailed down for every possible asymm algorithm, where useful
- [ ] Other digital signature and ssl related stuff (backburner, low uses cases). The only people that ever need this are using it for server frameworks.

Sphlib
- [ ] [Integrate sphlib hashing](http://www.saphir2.com/sphlib/)

Password hashing:
- [ ] PBKDF2 (wg)
- [ ] Pure Scala BCrypt
- [ ] Pure Scala SCrypt

Server-side:
- [ ] (Possibly?) Our own JWT implementation using our own algebras and primitives.
- [ ] Akka-http authentication (Priority 2)
- [ ] Play-http authentication (Optional, play already has silhouette)

BouncyCastle:
- [ ] MessageDigests
- [ ] Symmetric ciphers
- [ ] Asymmetric Ciphers
- [ ] KeyGenerators and key construction in general 4
- [ ] KeySpec
- [ ] Mac
- [ ] AlgorithmParameter and generators
- [ ] Other digital signature and ssl related stuff (backburner, low uses cases)

### Other things on the list:
- TESTING. TESTING. TESTING.
- Articles and education. We might not be opinionated about exact ciphers being used, but this is the equivalent of handing someone a gun with no education about shooting. There are so many different use cases: File integrity management, Token encryption, passwords (everyone and their mom is still on bcrypt and it's 2017 if anything we improve in our community it's getting rid of this), TLS, key exchange... so on and so forth. Tutorials on some of this stuff would be nice.
- . I think it's important to support the JCA's wacky inflatable world of use cases, but we _should_ provide sensible defaults that people can pop in and go. 
- Implementing some of these in pure scala, particularly the passwordhashers.

**Comment by jmcardon** [comment]
Moved roadmap to [wiki](https://github.com/jmcardon/tsec/wiki/RoadMap)

Closing this
